# frozen_string_literal: true

require "test_helper"

class CCYearEndStatement::CSVExtractorTest < ActiveSupport::TestCase
  FakeExtractor = Struct.new(:result) do
    def call(filename:)
      raise ArgumentError, "filename is required" if filename.blank?

      result
    end
  end

  test "requires a filename" do
    error = assert_raises(ArgumentError) do
      CCYearEndStatement::CSVExtractor.call(filename: nil)
    end

    assert_match(/filename is required/i, error.message)
  end

  test "raises when the CSV file is missing" do
    assert_raises(Errno::ENOENT) do
      CCYearEndStatement::CSVExtractor.call(filename: "/tmp/missing-year-end-summary.csv")
    end
  end

  test "rebuilds categories subcategories and transactions from a pipe-delimited CSV" do
    Dir.mktmpdir do |dir|
      path = File.join(dir, "year_end_transactions.csv")
      File.write(path, <<~CSV)
        date|category|subcategory|description|location|amount
        2025-07-01|Merchandise|Clothing|MENS WAREHOUSE 1534|JONESBORO, AR|740.61
        2025-07-08|Merchandise|Clothing|MENS WAREHOUSE 1534|JONESBORO, AR|249.08
        2025-07-23|Merchandise|Department Store|DILLARDS 406 TURTLE CR|JONESBORO, AR|179.03
        2025-05-09|Travel and Transportation|Hotels|COMFORT INNS|ORLANDO, FL|-100.0
      CSV

      result = CCYearEndStatement::CSVExtractor.call(filename: path)

      assert_equal path, result.filename
      assert_nil result.page_count
      assert_equal [ "Merchandise", "Travel and Transportation" ], result.categories.map(&:name)

      merchandise = result.categories.first
      assert_equal BigDecimal("1168.72"), merchandise.total
      assert_equal [ "Clothing", "Department Store" ], merchandise.subcategories.map(&:name)
      assert_equal BigDecimal("989.69"), merchandise.subcategories.first.total

      hotels = result.categories.last.subcategories.first
      assert_equal BigDecimal("-100.0"), hotels.total
      assert_equal Date.new(2025, 5, 9), hotels.transactions.first.date
      assert_equal "COMFORT INNS", hotels.transactions.first.description
      assert_equal "ORLANDO, FL", hotels.transactions.first.location
      assert_equal BigDecimal("-100.0"), hotels.transactions.first.amount

      assert_equal 4, result.transactions.size
      assert_equal BigDecimal("1068.72"), result.transactions.sum(&:amount)
    end
  end

  test "reads a CSV with a custom separator" do
    Dir.mktmpdir do |dir|
      path = File.join(dir, "year_end_transactions.csv")
      File.write(path, <<~CSV)
        date,category,subcategory,description,location,amount
        2025-11-12,Education,Education,UDEMY ONLINE COURSES,"UDEMY.COM, CA",30.36
      CSV

      result = CCYearEndStatement::CSVExtractor.call(filename: path, field_separator: ",")

      assert_equal [ "Education" ], result.categories.map(&:name)
      assert_equal BigDecimal("30.36"), result.categories.first.total
      assert_equal "Education", result.categories.first.subcategories.first.name
      assert_equal "UDEMY.COM, CA", result.transactions.first.location
    end
  end

  test "auto-detects a comma-separated CSV when no separator is passed" do
    Dir.mktmpdir do |dir|
      path = File.join(dir, "year_end_transactions.csv")
      File.write(path, <<~CSV)
        date,category,subcategory,description,location,amount
        2025-11-12,Education,Education,UDEMY ONLINE COURSES,"UDEMY.COM, CA",30.36
      CSV

      result = CCYearEndStatement::CSVExtractor.call(filename: path)

      assert_equal [ "Education" ], result.categories.map(&:name)
      assert_equal BigDecimal("30.36"), result.transactions.first.amount
      assert_equal "UDEMY.COM, CA", result.transactions.first.location
    end
  end

  test "rejects CSV files with unexpected headers" do
    Dir.mktmpdir do |dir|
      path = File.join(dir, "year_end_transactions.csv")
      File.write(path, <<~CSV)
        posted_on|category|subcategory|description|location|amount
        2025-11-12|Education|Education|UDEMY ONLINE COURSES|UDEMY.COM, CA|30.36
      CSV

      error = assert_raises(ArgumentError) do
        CCYearEndStatement::CSVExtractor.call(filename: path)
      end

      assert_match(/unexpected CSV headers/i, error.message)
    end
  end

  test "round-trips the output generated by CSV writer" do
    Dir.mktmpdir do |dir|
      source_path = File.join(dir, "statement.pdf")
      File.write(source_path, "pdf")

      csv_path = CCYearEndStatement::CSVWriter.call(
        filename: source_path,
        extractor: FakeExtractor.new(extractor_result)
      )

      result = CCYearEndStatement::CSVExtractor.call(filename: csv_path)

      assert_equal extractor_result.transactions, result.transactions
      assert_equal extractor_result.categories.map(&:name), result.categories.map(&:name)
      assert_equal extractor_result.categories.map(&:total), result.categories.map(&:total)
    end
  end

  private

  def extractor_result
    CCYearEndStatement::Extractor::Result.new(
      filename: "/tmp/statement.pdf",
      page_count: 1,
      categories: [
        CCYearEndStatement::Extractor::Category.new(
          name: "Merchandise",
          total: BigDecimal("740.61"),
          subcategories: [
            CCYearEndStatement::Extractor::Subcategory.new(
              name: "Clothing",
              total: BigDecimal("740.61"),
              transactions: [
                CCYearEndStatement::Extractor::Transaction.new(
                  date: Date.new(2025, 7, 1),
                  description: "MENS WAREHOUSE 1534",
                  location: "JONESBORO, AR",
                  amount: BigDecimal("740.61"),
                  category: "Merchandise",
                  subcategory: "Clothing"
                )
              ]
            )
          ]
        ),
        CCYearEndStatement::Extractor::Category.new(
          name: "Travel and Transportation",
          total: BigDecimal("-100.0"),
          subcategories: [
            CCYearEndStatement::Extractor::Subcategory.new(
              name: "Hotels",
              total: BigDecimal("-100.0"),
              transactions: [
                CCYearEndStatement::Extractor::Transaction.new(
                  date: Date.new(2025, 5, 9),
                  description: "COMFORT INNS",
                  location: "ORLANDO, FL",
                  amount: BigDecimal("-100.0"),
                  category: "Travel and Transportation",
                  subcategory: "Hotels"
                )
              ]
            )
          ]
        )
      ]
    )
  end
end
